### ISSUE TITLE
Reset the Zoom

### ISSUE THREAD

**Issue by binu8051** [damianhoppe/RTSP-Player#13]
Hi, using the code and works fine, Thanks.
Need the Code to reset the camera zoom to the default or initial value.

**Comment by damianhoppe** [comment]
Hi,
the view class has a method `onConfigurationChanged`, which is called when a change in device configuration is detected.
Currently, this method only responsible for resetting the zoom to the default value, so at the moment you can think of it as a zoom reset method, or you can look at the contents of this method for a more detailed look at the code responsible for resetting the zoom.

Also note that the application also has support for two rendering methods: using _GLSurfaceView_ and _TextureView_. Both classes inherit from an interface that defines the `onConfigurationChanged` method, and the implementation of this method varies depending on the view used, so if you are interested in the exact implementation of this method, you will have to look at the corresponding _MyGLSurfaceView_ class or _ZoomableTextureView_ class.

I hope I helped, if you have any further questions, please feel free to ask.
Kind regards

**Comment by damianhoppe** [comment]
There is a new update so I would like to update my answer.
The view class responsible for handling the player and gestures has been unified, it is _PlayerViewContainer_ it has the `resetTransformation()` method, which is responsible for resetting the zoom.

For now, I am closing the issue, if there is another question related to this topic, please reopen it
