### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by bobocancan** [damianhoppe/RTSP-Player#8]
I have a streaming source that has a resolution of 3456  * 1000 and the app can shows only part of the video.

**Comment by damianhoppe** [comment]
Hello
Yes, I can also confirm that this is problem. Thanks for reporting this bug to me. In the near future, I will also focus on solving this problem.
I also apologize for my break which unfortunately was caused by many factors beyond my control
Regards: D

**Comment by bobocancan** [comment]
Hi mate,

It's my honour to have used your wonderful app. No need to apologize at
all. Thanks for sharing your work with us. 😊


Regards
Bo

Damian Hoppe ***@***.***> 于 2022年4月5日周二 21:47写道：

**Comment by damianhoppe** [comment]
The problem should be solved in the latest update (1.7).
If you have new questions or continue to encounter this issue, please reopen this issue and let me know along with additional information about your device model and video stream parameters.
Regards

**Comment by damianhoppe** [comment]
The problem should be solved in the latest update (1.7).
If you have new questions or continue to encounter this issue, please reopen this issue and let me know along with additional information about your device model and video stream parameters.
Regards
