### ISSUE TITLE
Possible to adapt the app to Material Design 3?

### ISSUE THREAD

**Issue by robbie99us** [damianhoppe/RTSP-Player#9]
This app has saved me a lot of time that it deserves a shortcut in my home screen. I'd love to see the icon upgraded to match other icons and the wallpaper. Thanks for the app!

**Comment by damianhoppe** [comment]
Hi,

Thank you for some kind words :D
I am currently working on a new update that will also include an interface (icon too) update  to Material Design 3.
I apologize also for my long break.

Regards,
Damian Hoppe

**Comment by damianhoppe** [comment]
Implemented 🏆
The update has been made available on Google Play and in the releases tab of the repository
